In [1]:
import pandas as pd
datename = '180101To220825'
pricefilename = '{}{}{}'.format('data/price_',datename,'.pkl')
premfilename = '{}{}{}'.format('data/prem_',datename,'.pkl')
sizefilename = '{}{}{}'.format('data/size_',datename,'.pkl')
price100filename = '{}{}{}'.format('data/price100_',datename,'.pkl')
prem100filename = '{}{}{}'.format('data/prem100_',datename,'.pkl')
size100filename = '{}{}{}'.format('data/size100_',datename,'.pkl')

pricedf=pd.read_pickle(pricefilename) #直接读取pkl数据文件。
pricedf

tickerBond,110030,110031,110032,110033,110034,110038,110039,110040,110041,110042,...,128136,128137,128138,128139,128140,128141,128142,128143,128144,128145
tradeDate,,,,,,,,,,,,,,,,,,,,,
2018-01-02,105.40,100.09,126.64,118.08,110.44,107.550,107.17,111.53,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,105.46,100.37,127.53,120.01,112.74,110.000,108.00,112.31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,105.60,100.38,127.07,120.39,114.00,111.100,110.35,112.25,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,109.34,101.40,130.14,123.89,114.00,112.570,112.95,113.29,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,109.76,100.67,132.33,124.40,113.95,113.150,112.03,113.68,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,NaN,NaN,NaN,NaN,NaN,130.649,NaN,NaN,NaN,NaN,...,117.999,135.000,120.97,293.0,177.000,152.414,113.900,136.100,124.000,153.500
2022-08-22,NaN,NaN,NaN,NaN,NaN,130.117,NaN,NaN,NaN,NaN,...,118.777,138.030,121.23,NaN,174.650,157.040,114.582,133.960,124.420,150.276
2022-08-23,NaN,NaN,NaN,NaN,NaN,128.444,NaN,NaN,NaN,NaN,...,118.660,138.131,121.98,NaN,170.200,151.020,114.250,136.849,123.566,149.899
2022-08-24,NaN,NaN,NaN,NaN,NaN,125.486,NaN,NaN,NaN,NaN,...,116.100,134.813,120.31,NaN,158.400,146.041,113.400,131.200,122.779,149.583
2022-08-25,NaN,NaN,NaN,NaN,NaN,124.387,NaN,NaN,NaN,NaN,...,116.062,132.621,119.77,NaN,160.699,143.826,112.700,128.500,123.239,143.979

In [2]:
import numpy as np
def fensu01(abc):#数值小，分数大！
    dt = abc.T
    median = dt.quantile(0.5)   # 找出中位数
    new_median = (abs((dt - median)).quantile(0.5))   # 偏差值的中位数
    dt_up = median + 3*new_median    # 上限
    dt_down = median - 3*new_median  # 下限
    X_return = dt.clip(dt_down, dt_up, axis=1)    # 超出上下限的值，赋值为上下限
    r_max = np.max(X_return)
    r_min = np.min(X_return)
    X_fensu01 = (r_max-X_return)/(r_max-r_min)
    Y = X_fensu01.T
    return Y

In [4]:
price100df = fensu01(pricedf)
price100df

tickerBond,110030,110031,110032,110033,110034,110038,110039,110040,110041,110042,...,128136,128137,128138,128139,128140,128141,128142,128143,128144,128145
tradeDate,,,,,,,,,,,,,,,,,,,,,
2018-01-02,0.626549,0.783186,0.0,0.252507,0.477876,0.563127,0.574336,0.445723,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,0.565478,0.745001,0.0,0.052305,0.308715,0.405354,0.475893,0.323881,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,0.594756,0.763716,0.0,0.116038,0.322868,0.416734,0.441010,0.379511,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,0.544815,0.776478,0.0,0.120295,0.408852,0.450575,0.439488,0.429568,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,0.540644,0.800641,0.0,0.121904,0.420800,0.443682,0.475716,0.428522,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,NaN,NaN,NaN,NaN,NaN,0.506970,NaN,NaN,NaN,NaN,...,0.699168,0.440863,0.654028,0.0,0.0,0.176283,0.761446,0.424150,0.607992,0.159783
2022-08-22,NaN,NaN,NaN,NaN,NaN,0.508461,NaN,NaN,NaN,NaN,...,0.681805,0.387502,0.644308,NaN,0.0,0.096914,0.745930,0.449716,0.595546,0.200309
2022-08-23,NaN,NaN,NaN,NaN,NaN,0.541301,NaN,NaN,NaN,NaN,...,0.691771,0.392323,0.640712,NaN,0.0,0.194101,0.759593,0.412039,0.616320,0.211341
2022-08-24,NaN,NaN,NaN,NaN,NaN,0.538239,NaN,NaN,NaN,NaN,...,0.697119,0.380358,0.625855,NaN,0.0,0.190297,0.742823,0.441516,0.584061,0.130341
2022-08-25,NaN,NaN,NaN,NaN,NaN,0.523793,NaN,NaN,NaN,NaN,...,0.673062,0.376156,0.606577,NaN,0.0,0.175249,0.733343,0.450047,0.544377,0.172506

In [6]:
premdf=pd.read_pickle(premfilename)
premdf

tickerBond,110030,110031,110032,110033,110034,110038,110039,110040,110041,110042,...,128136,128137,128138,128139,128140,128141,128142,128143,128144,128145
tradeDate,,,,,,,,,,,,,,,,,,,,,
2018-01-02,32.2523,97.8684,-0.7452,1.8888,5.9766,15.2441,5.5124,4.6499,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,31.8705,96.4259,0.0578,3.5541,8.4646,13.0295,7.3602,6.7098,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,31.8179,96.7153,0.0137,3.8820,9.2229,14.1312,7.4399,6.8284,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,28.7189,98.2603,0.8279,3.4569,9.9625,15.5835,7.5325,7.8774,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,26.7404,101.7170,-0.4846,3.1010,11.0712,14.2636,9.0756,7.5401,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,NaN,NaN,NaN,NaN,NaN,20.9594,NaN,NaN,NaN,NaN,...,82.2043,34.6563,137.3307,7.3896,17.6706,9.8081,90.3505,39.7514,39.2978,10.1103
2022-08-22,NaN,NaN,NaN,NaN,NaN,21.2077,NaN,NaN,NaN,NaN,...,78.7225,35.7047,142.7486,NaN,19.6921,11.6523,90.2805,44.1154,36.2173,13.4137
2022-08-23,NaN,NaN,NaN,NaN,NaN,23.2368,NaN,NaN,NaN,NaN,...,78.5930,40.3828,143.4774,NaN,19.2948,9.1551,90.5893,44.3945,33.7139,12.9657
2022-08-24,NaN,NaN,NaN,NaN,NaN,22.8897,NaN,NaN,NaN,NaN,...,82.9406,42.7768,148.3978,NaN,18.2022,9.5482,93.0212,44.2172,36.2859,8.7213
2022-08-25,NaN,NaN,NaN,NaN,NaN,22.4468,NaN,NaN,NaN,NaN,...,77.7872,40.0767,142.1311,NaN,20.1916,7.8350,90.2458,44.7774,31.4549,7.0349

In [5]:
prem100df = fensu01(premdf)
prem100df

tickerBond,110030,110031,110032,110033,110034,110038,110039,110040,110041,110042,...,128136,128137,128138,128139,128140,128141,128142,128143,128144,128145
tradeDate,,,,,,,,,,,,,,,,,,,,,
2018-01-02,0.000000,0.0,0.985677,0.897077,0.759576,0.447844,0.775190,0.804202,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,0.000000,0.0,0.972097,0.831707,0.634531,0.451232,0.678877,0.704993,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,0.000000,0.0,1.000000,0.871700,0.694557,0.531763,0.753694,0.773976,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,0.000000,0.0,1.000000,0.905273,0.670867,0.468335,0.758424,0.745996,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,0.064459,0.0,1.000000,0.876787,0.602904,0.493203,0.671480,0.724245,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,NaN,NaN,NaN,NaN,NaN,0.759980,NaN,NaN,NaN,NaN,...,0.100954,0.612595,0.0,0.905998,0.795370,0.879974,0.013297,0.557769,0.562650,0.876722
2022-08-22,NaN,NaN,NaN,NaN,NaN,0.754153,NaN,NaN,NaN,NaN,...,0.117695,0.593730,0.0,NaN,0.770925,0.859893,0.000000,0.500657,0.588057,0.840402
2022-08-23,NaN,NaN,NaN,NaN,NaN,0.731643,NaN,NaN,NaN,NaN,...,0.136480,0.547298,0.0,NaN,0.774026,0.883043,0.007501,0.504166,0.618998,0.842073
2022-08-24,NaN,NaN,NaN,NaN,NaN,0.762628,NaN,NaN,NaN,NaN,...,0.166476,0.565200,0.0,NaN,0.809163,0.895075,0.066402,0.550900,0.629638,0.903284
2022-08-25,NaN,NaN,NaN,NaN,NaN,0.758795,NaN,NaN,NaN,NaN,...,0.190197,0.577656,0.0,NaN,0.781967,0.908925,0.062190,0.529358,0.666241,0.917146

In [7]:
sizedf=pd.read_pickle(sizefilename)
sizedf

tickerBond,110030,110031,110032,110033,110034,110038,110039,110040,110041,110042,...,128136,128137,128138,128139,128140,128141,128142,128143,128144,128145
tradeDate,,,,,,,,,,,,,,,,,,,,,
2018-01-02,9.77498,23.994843,43.236470,14.62674,14.993263,8.431600,16.0,18.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,9.77498,23.994843,43.120792,14.62674,14.993263,8.431600,16.0,18.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,9.77498,23.994843,43.046653,14.62674,14.993263,8.431600,16.0,18.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,9.77498,23.994843,43.043384,14.62672,14.993263,8.431600,16.0,18.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,9.77477,23.994843,42.124041,14.62671,14.993263,8.431600,16.0,18.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,NaN,NaN,NaN,NaN,NaN,6.301665,NaN,NaN,NaN,NaN,...,29.992931,5.994073,4.199084,0.359963,10.896371,12.701485,7.179784,2.441972,9.794158,3.768341
2022-08-22,NaN,NaN,NaN,NaN,NaN,6.301665,NaN,NaN,NaN,NaN,...,29.992931,5.994073,4.199084,NaN,10.896341,12.701485,7.179784,2.441972,9.794158,3.768341
2022-08-23,NaN,NaN,NaN,NaN,NaN,6.301665,NaN,NaN,NaN,NaN,...,29.992931,5.994073,4.199084,NaN,10.896341,12.701485,7.179784,2.441972,9.794158,3.768341
2022-08-24,NaN,NaN,NaN,NaN,NaN,6.301665,NaN,NaN,NaN,NaN,...,29.992931,5.994073,4.199084,NaN,10.896321,12.701485,7.179784,2.441972,9.794158,3.768321
2022-08-25,NaN,NaN,NaN,NaN,NaN,6.301665,NaN,NaN,NaN,NaN,...,29.992931,5.994073,4.199084,NaN,10.896321,12.701485,7.179784,2.441972,9.794158,3.768321

In [9]:
size100df = fensu01(sizedf)
size100df

tickerBond,110030,110031,110032,110033,110034,110038,110039,110040,110041,110042,...,128136,128137,128138,128139,128140,128141,128142,128143,128144,128145
tradeDate,,,,,,,,,,,,,,,,,,,,,
2018-01-02,0.637135,0.0,0.0,0.414984,0.398202,0.698645,0.352106,0.260531,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,0.628548,0.0,0.0,0.401140,0.383961,0.691513,0.336774,0.243032,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,0.628548,0.0,0.0,0.401140,0.383961,0.691513,0.336774,0.243032,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,0.628547,0.0,0.0,0.401140,0.383960,0.691513,0.336773,0.243031,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-08,0.628557,0.0,0.0,0.401140,0.383960,0.691513,0.336773,0.243030,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-19,NaN,NaN,NaN,NaN,NaN,0.630841,NaN,NaN,NaN,NaN,...,0.0,0.648930,0.754493,0.980271,0.360627,0.254469,0.579199,0.857829,0.425448,0.779825
2022-08-22,NaN,NaN,NaN,NaN,NaN,0.631852,NaN,NaN,NaN,NaN,...,0.0,0.649892,0.755166,NaN,0.362381,0.256512,0.580352,0.858218,0.427022,0.780428
2022-08-23,NaN,NaN,NaN,NaN,NaN,0.630465,NaN,NaN,NaN,NaN,...,0.0,0.648573,0.754243,NaN,0.359979,0.253711,0.578771,0.857684,0.424864,0.779601
2022-08-24,NaN,NaN,NaN,NaN,NaN,0.629443,NaN,NaN,NaN,NaN,...,0.0,0.647601,0.753564,NaN,0.358209,0.251646,0.577605,0.857290,0.423272,0.778993
2022-08-25,NaN,NaN,NaN,NaN,NaN,0.628282,NaN,NaN,NaN,NaN,...,0.0,0.646497,0.752791,NaN,0.356198,0.249301,0.576282,0.856843,0.421465,0.778300

In [ ]:
def df2pkl():   #数据加工后的输出函数。
    price100df.to_pickle(price100filename)
    prem100df.to_pickle(prem100filename)
    size100df.to_pickle(size100filename)
    return
#df2pkl()    #取消函数名前的"#"则将数据输出至pkl文件。